services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 4000:4000
    volumes:
      - .:/app
    networks:
      - next
  
  db:
    image: postgres:12
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: next_dev
    networks:
      - next

networks:
  next:
    driver: bridge