---

- name: Install ASDF Deps
  ansible.builtin.apt:
    name:
      - autoconf
      - automake
      - build-essential
      - curl
      - git
      - libffi-dev
      - libncurses5-dev
      - libreadline-dev
      - libssl-dev
      - libtool
      - libxslt-dev
      - libyaml-dev
      - unzip
    state: present
    install_recommends: yes


