---
- name: Security packages
  ansible.builtin.apt:
    state: present
    name:
      - fail2ban
      - debian-goodies
      - apt-listchanges
      - acl

- name: Set timezone to Europe/Amsterdam
  community.general.timezone:
    name: Europe/Amsterdam

- name: Setup Slack notification script for shutdowns
  ansible.builtin.template:
    src: templates/notify_slack_on_shutdown.sh
    dest: /usr/local/bin/notify_slack_on_shutdown
    owner: root
    group: root
    mode: 0755

- name: Systemd service for shutdown notification
  ansible.builtin.template:
    src: templates/notify_slack_on_shutdown.service
    dest: '/lib/systemd/system/notify_slack_on_shutdown.service'
    owner: root
    group: root
    mode: 0644
  notify: Reload Systemd

- name: Setup Slack shutdown notification service
  ansible.builtin.service:
    name: 'notify_slack_on_shutdown'
    enabled: yes
    daemon_reload: true

- name: Setup Slack notification script for SSH login
  ansible.builtin.template:
    src: templates/pam_slack.sh
    dest: /usr/local/bin/pam_slack
    owner: root
    group: root
    mode: 0755

- name: Enable PAM Slack notification
  ansible.builtin.lineinfile:
    path: /etc/pam.d/sshd
    regex: "slack"
    line: "session required pam_exec.so /usr/local/bin/pam_slack"

- name: SSH config
  ansible.builtin.template:
    src: templates/sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0600
  notify: Reload SSH

- name: Unattended upgrades conf
  ansible.builtin.template:
      src: templates/unattended-upgrades.conf
      dest: /etc/apt/apt.conf.d/50unattended-upgrades

- name: Apt daily conf directory
  ansible.builtin.file:
      path: /etc/systemd/system/apt-daily.timer.d
      state: directory

- name: Unattended upgrades schedule override
  ansible.builtin.template:
      src: templates/apt-daily.timer.override.conf
      dest: /etc/systemd/system/apt-daily.timer.d/override.conf

- name: Setup unattended upgrades
  apt:
    name: unattended-upgrades
    state: present

- name: libpam quality (password strength)
  ansible.builtin.apt:
    name: libpam-pwquality
    state: present
    # FIXME: add some more rules to lock down

- name: Rate limit ssh (firewall)
  ansible.builtin.ufw:
    rule: limit
    port: ssh
    proto: tcp

- name: Allow outgoing (firewall)
  ansible.builtin.ufw:
    policy: allow
    direction: outgoing

- name: Deny incoming
  ansible.builtin.ufw:
    state: enabled
    policy: deny
    direction: incoming
