name: Docker Release

on:
  workflow_dispatch:
    inputs:
      bundle:
        description: "Bundle ID (link / next etc.)"
        required: true
        default: "next"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      MIX_ENV: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Tag name
        id: tag
        run: echo ::set-output "name=TAG::$(date +%F)_${{github.run_number}}"

      - name: Log in to the Container registry
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@35e9aff4f5d665b5aa8a8f2adffaf8a1b5f49cc0
        with:
          images: |
            ${{env.REGISTRY}}/eyra/${{github.event.inputs.bundle}}
          tags: |
            type=raw,value=${{steps.tag.outputs.tag}}
            type=raw,value=latest
          # type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825
        with:
          context: core
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BUNDLE=${{github.event.inputs.bundle}}
            VERSION=${{steps.tag.outputs.tag}}
