name: Docs

on:
  push:
    branches:
      - master

jobs:
  docs:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: setup-elixir
        uses: erlef/setup-elixir@v1
        with:
          otp-version: '24.0.1'
          elixir-version: '1.12.1'

      - name: Setup the Elixir project
        run: make deps

      - name: Generate the docs
        run: make docs

      - name: Publish documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc/
