name: Release

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch name"
        required: true
        default: "main"
        type: string
      bundle:
        description: "Bundle ID (next, self)"
        required: true
        default: "next"

jobs:
  build-release:
    runs-on: ubuntu-20.04
    env:
      MIX_ENV: prod

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Set TAG and VERSION
        id: vars
        run: |
          TAG="${{ inputs.bundle }}_$(date +%F)_${{ github.run_number }}"
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "VERSION=$TAG" >> $GITHUB_ENV
        shell: bash

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image with cache
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          tags: next-platform:latest
          push: false
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run build inside Docker
        run: |
          docker run --rm \
            -e MIX_ENV=$MIX_ENV \
            -e BUNDLE=${{ inputs.bundle }} \
            -e VERSION=$VERSION \
            -v ${{ github.workspace }}:/app \
            next-platform:latest \
            bash -c "cd /app/core && mix deps.get && ./scripts/build-frontend && ./scripts/build-release"

      - name: Ensure permissions are correct for tar
        run: chmod -R a+r core/${{ env.VERSION }}

      - name: Archive release
        working-directory: core
        run: |
          tar cfj "${VERSION}.tar.bz2" "${VERSION}"

      - name: Verify artifact
        run: ls -l core/*.tar.bz2

      # - name: Create GitHub Release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     tag_name: ${{ env.VERSION }}
      #     prerelease: false
      #     fail_on_unmatched_files: true
      #     files: |
      #       core/${{ env.VERSION }}.tar.bz2

      - name: Upload release artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-artifact
          path: core/${{ env.VERSION }}.tar.bz2
