name: Test

on:
  push:
    branches-ignore:
      - master

jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      GOOGLE_AUTH_CLIENT_ID: ${{ secrets.GOOGLE_AUTH_CLIENT_ID }}
      GOOGLE_AUTH_CLIENT_SECRET: ${{ secrets.GOOGLE_AUTH_CLIENT_SECRET }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Checkout the whole branch, needed for deployment

      - name: Run the tests
        run: docker-compose run ci
