name: Test & Lint

on:
  push:
    branches-ignore:
      - master

jobs:
  test:
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: link
          POSTGRES_PASSWORD: supersecret
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      MIX_ENV: test
      MIX_HOME: ${{ github.workspace }}/mix_home 
      MIX_BUILD_ROOT: ${{ github.workspace }}/mix_build 
      POSTGRES_USER: link
      POSTGRES_PASS: supersecret
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - id: setup-elixir
        uses: erlef/setup-elixir@v1
        with:
          otp-version: '23.2'
          elixir-version: '1.11.3'

      - name: Setup the Elixir project
        run: make deps

      # Setup caching (mostly for Dialyzer)
      - uses: actions/cache@v2
        id: cache-mix-home
        with:
          path: mix_home
          key: "mix-${{ runner.os }}-${{ steps.setup-elixir.outputs.otp-version }}-Elixir-${{ steps.setup-elixir.outputs.elixir-version }}"

      - uses: actions/cache@v2
        id: cache-mix-build
        with:
          path: mix_build
          key: "mix-${{ runner.os }}-${{ steps.setup-elixir.outputs.otp-version }}-Elixir-${{ steps.setup-elixir.outputs.elixir-version }}"

      - run: tree $MIX_HOME
      - run: tree $MIX_BUILD

      - name: Format
        run: make format
        continue-on-error: true

      - name: Commit formatted code
        uses: EndBug/add-and-commit@v6
        with:
          add: '.'
          message: 'Formatted code'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Dialyzer
        run: make dialyzer

      - name: Compile
        run: make compile

      - name: Test
        run: make test

      - name: Credo
        run: make credo

      - name: Format
        run: make format
