name: Test & Lint

on:
  push:
    tags:
      - '*'

jobs:
  tagged-release:
    runs-on: ubuntu-20.04
    env:
      MIX_ENV: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - id: setup-elixir
        uses: erlef/setup-elixir@v1
        with:
          otp-version: '24.0.1'
          elixir-version: '1.12.1'

      - name: Setup the Elixir project
        run: make deps

      - name: Install Node deps
        run: npm install
        working-directory: core/assets

      - name: Build release
        run: mix release --overwrite --path "../core-release-$GITHUB_REF"
        working-directory: core

      - name: Archive release
        run: tar cfj "core-release-$GITHUB_REF.tar.bz2" "core-release-$GITHUB_REF"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            "core-release-$GITHUB_REF.tar.bz2"
